################################################################################
##########################    CONFIGURATION    #################################
################################################################################

#/!\ WARNING /!\
#Be sure to always keep the following synthax for each parameters: my_param[space]:[space]my_value

################################################################################
#######################    GENERAL PARAMETERS    ###############################
################################################################################
#fastq location / Define path where the "barcode*" rep are stored
data_loc : fastq/ONT_run_240130_WG/
#output location / Define path where storing analysis results 
result_loc : results_VHB_240130_WG/
#custom reference file to use /  Path to fastafile containing reference sequences for blast
ref_loc : data/ref/HBV_subtype.fasta
#core number / Define number of threads to use for the analysis
thread_number : 32
#memory cost in mb / Define number of threads to use for the analysis
mem_cost : 400000
#################################################################################

#################################################################################
##################    TRIMMING/FILTERING PARAMETERS    ##########################
#################################################################################
#min length for read filtering
min_length : 1000
#max length for read filtering
max_length : 5000
#average read quality for filtering
min_qual_ONT : 12
#Remove N 5' nucleotides from each filtered read 
head_trim : 0
#Remove N 3' nucleotides from each filtered read 
tail_trim : 0
#Remove read blasting with a bitscore above the threshold
bitscore_min : 0
#################################################################################

#################################################################################
#########################    READ CORRECTION   #0################################
#################################################################################
#enable or not read correction. Can be high time/ressource consuming depending on the following parameters.
correction : false
#average coverage of reads on the reference. /!\ This parameter significantly increase computing time if too high!
cov_correction : 100000
#corrected error rate for ONT. See the readme file for more information
error_rate : 0.105
#################################################################################

#################################################################################
##########################    PRIMER TRIMMING   #################################
#################################################################################
#enable or not primer trimming if you have a bed based on the used reference
do_amplicon_removal : false
#path to the bed file with primer coordinates
bedfilepath : data/amplicon/midnight_primers.bed
#################################################################################

#################################################################################
####################    VARIANT CALLING PARAMETERS    ###########################
#################################################################################
#maximum depth for samtools mpileup
max_depth : 10000000
#base quality cutoff for samtools mpileup
basequality : 0
#################################################################################

#################################################################################
#######################    CONSENSUS PARAMETERS    ##############################
#################################################################################
#minor variant frequency
Vfreq : 0.08
#minimun coverage necessary to generate a consensus / N is called if below threshold
min_cov : 20
#################################################################################

#################################################################################
####################    MULTI-INFECTION PARAMETER    ############################
#################################################################################
#Multi infection threshold cutoff in percent / cutoff=count(Blastref_reads)/count(majoritaryBlastref_reads)*100
MI_cutoff : 30
#################################################################################

#################################################################################
######################    HBV MUTATION RESEARCH    ##############################
#################################################################################
#set this paramater to "TRUE" will initiate optionnal mutation research for specitif HBV dataset.
HBV_mut : FALSE
#location of the mutation table.
path_table : mutation_table/
#variant frequency under the threshold will be removed from filtered table. Should be between 0 and 100
freq_min : 8
#If using reference without primers, correct position in the mutation table. Could be Positive or negative.
window_pos: 0
#################################################################################
